from typing import Callable

def SetEazyTitle(z:str)->None:...
def Alert(message:str,icon:str)->None:...
def Error(x: str) -> None: ...
def ErrorText(x: str)->None:...
def Info(dih: str) -> None: ...
def Warning(dih: str) -> None: ...
def Ask(dih: str, nih: bool, **l) -> None: ...
def Colored(Color: str, Text: str) -> None: ...
def Beep(Frequency: int, duration: int) -> None: ...
def Countdown(timeleft: int) -> None: ...
def BeepCountdown(timeleft: int) -> None: ...
def Copy(a: str)->None:...
def Paste()->None:...
def Busy(act: str)->None:...
def ReopenAsAdmin()->None:...
def FlashWindow(duration: int)->None:...
def SendNotification(text: str,duration: str)->None:...
def CheckNetwork()->None:...

CautionIcon:int
InfoIcon:int
ErrorIcon:int
QuestionIcon:int

white:str
blue:str
cyan:str
green:str
magenta:str
yellow:str
red:str
black:str
lightwhite:str
lightblue:str
lightcyan:str
lightgreen:str
lightmagenta:str
lightyellow:str
lightred:str
lightblack:str

__all__=[
 "Error",
 "Info",
 "Warning",
 "Ask",
 "Colored",
 "Beep",
 "Countdown",
 "BeepCountdown",
 "white","blue","cyan","green","magenta","yellow","red","black",
 "lightwhite","lightblue","lightcyan","lightgreen",
 "lightmagenta","lightyellow","lightred","lightblack"
]
